title: "overlake.bio/documentation"
description: "Documentation"
url: "https://docs.overlake.bio" # your site URL
baseurl: ""

theme: just-the-docs
color_scheme: water

# Enable search (optional)
search_enabled: true

# Navigation structure (optional)
nav_sort: case_insensitive

# Build settings
markdown: kramdown
highlighter: rouge

# Math support
math: mathjax
