title: "overlake.bio/docs"
description: "Documentation"
url: "https://docs.overlake.bio" # your site URL
baseurl: ""

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Enable search (optional)
search_enabled: true

# Navigation structure (optional)
nav_sort: case_insensitive

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme
